version: '3.4'

services:
  postgres:
    image: postgres
    container_name: vote_monitor_postgres
    env_file:
      .env
    ports:
      - 5432:5432

  migrator:
    build:
      context: .
      dockerfile: api/VotingIrregularities.Domain.Migrator/Dockerfile
    container_name: vote_monitor_migrator
    env_file:
      .env
    depends_on:
      - "postgres"
